version: "3.9"
networks:
  inception:
    name: inception
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/aceauses/data/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/aceauses/data/wordpress
      o: bind
services:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    restart: unless-stopped