version: "3"
networks:
  inception:
    name: inception
services:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    networks:
      - inception
    ports:
      - "3306"
    volumes:
      - ../volumes/mariadb:/var/lib/mysql
    env_file:
      - .env
    # restart: unless-stopped
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - "9000"
    volumes:
      - ../volumes/wordpress:/var/www/html
    # restart: unless-stopped
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - ../volumes/nginx:/var/www/html
    # restart: unless-stopped